name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: cargo check
    - name: Check no features
      run: cargo check --no-default-features
    - name: Run tests
      run: cargo test --no-fail-fast
    - name: Run tests no features
      run: cargo test --no-default-features --no-fail-fast
