name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: cargo check --verbose
    - name: Check no features
      run: cargo check --no-default-features --no-fail-fast --verbose 
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests no features
      run: cargo test --no-default-features --no-fail-fast --verbose
